server:
  port: 80

logging:
  level:
    root: debug
#    com.avia.mtp: debug

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/avia_mtp
    username: root
    password: zhangjia
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
